#!/usr/bin/env python3
import argparse
import webbrowser as wb
from launcher import Launcher

parser = argparse.ArgumentParser(description='Launch an ec2 instance')
parser.add_argument('--size', '-s', type=str, nargs='?', default='test')

args = parser.parse_args()

launcher = Launcher()
image_id, public_nds = launcher.launch_instance(args.size)

wb.open(f"http://{public_dns}:80", 1)

stop = "no"
while stop != "yes":
    stop = input("Stop Instance?")

launcher.stop_instance(image_id)
